# 发行源码 | Release the source code

name: release-please

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      # Create release
      # REF https://github.com/marketplace/actions/release-please-action
      - name: Create release
        uses: googleapis/release-please-action@v4
        id: release
        with:
          # A GitHub secret token, the action defaults to using the special secrets.GITHUB_TOKEN
          # REF https://github.com/marketplace/actions/release-please-action#github-credentials
          token: ${{ secrets.PAT_ACTIONS }}

          # If specified, defines the release strategy to use for the repository. Reference Release types supported
          release-type: node

          # branch to open pull release PR against (detected by default)
          target-branch: main

          # Path to the release-please config in the repository. Defaults to release-please-config.json
          # config-file: release-please-config.json

          # Path to the release-please versions manifest. Defaults to .release-please-manifest.json
          # manifest-file: .release-please-manifest.json
